name: stock_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.0 # to create the PIN-input field
  carousel_slider: ^5.0.0 # for the news carousel

  # New dependencies for API and storage
  http: ^1.1.0                    # For API calls to Marketstack
  shared_preferences: ^2.2.2      # For local storage
  sqflite: ^2.3.0                # For local database (optional)
  path: ^1.8.3                   # For database path
  intl: ^0.18.1                  # For date formatting
  xml: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# After updating this file, run these commands:
# flutter pub get
# flutter pub upgrade